/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Program;

/**
 *
 * @author francis
 */
public class Assessment extends javax.swing.JFrame {

    /**
     * Creates new form TeacherQualitiesA
     */
    public Assessment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        RedPanel = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        YellowPanel = new javax.swing.JPanel();
        FirstChoices = new javax.swing.JPanel();
        FirstStronglyDisagree = new javax.swing.JRadioButton();
        FirstDisagree = new javax.swing.JRadioButton();
        FirstAgree = new javax.swing.JRadioButton();
        FirstStronglyAgree = new javax.swing.JRadioButton();
        FirstQuestion = new javax.swing.JLabel();
        SecondQuestion = new javax.swing.JLabel();
        ThirdQuestion = new javax.swing.JLabel();
        SecondChoices = new javax.swing.JPanel();
        SecondStronglyDisagree = new javax.swing.JRadioButton();
        SecondDisagree = new javax.swing.JRadioButton();
        SecondAgree = new javax.swing.JRadioButton();
        SecondStronglyAgree = new javax.swing.JRadioButton();
        ThirdChoices = new javax.swing.JPanel();
        ThirdStronglyDisagree = new javax.swing.JRadioButton();
        ThirdDisagree = new javax.swing.JRadioButton();
        ThirdAgree = new javax.swing.JRadioButton();
        ThirdStronglyAgree = new javax.swing.JRadioButton();
        FourthQuestion = new javax.swing.JLabel();
        FourthChoices = new javax.swing.JPanel();
        FourthStronglyDisagree = new javax.swing.JRadioButton();
        FourthDisagree = new javax.swing.JRadioButton();
        FourthAgree = new javax.swing.JRadioButton();
        FourthStronglyAgree = new javax.swing.JRadioButton();
        FifthQuestion = new javax.swing.JLabel();
        FifthChoices = new javax.swing.JPanel();
        FifthStronglyDisagree = new javax.swing.JRadioButton();
        FifthDisagree = new javax.swing.JRadioButton();
        FifthAgree = new javax.swing.JRadioButton();
        FifthStronglyAgree = new javax.swing.JRadioButton();
        Next = new javax.swing.JButton();
        Back = new javax.swing.JButton();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(730, 740));

        RedPanel.setBackground(new java.awt.Color(0, 102, 51));

        Title.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Title.setText("ASSESSMENT");

        javax.swing.GroupLayout RedPanelLayout = new javax.swing.GroupLayout(RedPanel);
        RedPanel.setLayout(RedPanelLayout);
        RedPanelLayout.setHorizontalGroup(
            RedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RedPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RedPanelLayout.setVerticalGroup(
            RedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RedPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        YellowPanel.setBackground(new java.awt.Color(153, 255, 153));

        FirstChoices.setBackground(new java.awt.Color(0, 102, 51));

        FirstStronglyDisagree.setBackground(new java.awt.Color(0, 102, 51));
        FirstStronglyDisagree.setForeground(new java.awt.Color(255, 204, 0));
        FirstStronglyDisagree.setText("Strongly Disagree");
        FirstStronglyDisagree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstStronglyDisagreeActionPerformed(evt);
            }
        });

        FirstDisagree.setBackground(new java.awt.Color(0, 102, 51));
        FirstDisagree.setForeground(new java.awt.Color(255, 204, 0));
        FirstDisagree.setText("Disagree");
        FirstDisagree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstDisagreeActionPerformed(evt);
            }
        });

        FirstAgree.setBackground(new java.awt.Color(0, 102, 51));
        FirstAgree.setForeground(new java.awt.Color(255, 204, 0));
        FirstAgree.setText("Agree");
        FirstAgree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstAgreeActionPerformed(evt);
            }
        });

        FirstStronglyAgree.setBackground(new java.awt.Color(0, 102, 51));
        FirstStronglyAgree.setForeground(new java.awt.Color(255, 204, 0));
        FirstStronglyAgree.setText("Strongly Agree");
        FirstStronglyAgree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstStronglyAgreeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FirstChoicesLayout = new javax.swing.GroupLayout(FirstChoices);
        FirstChoices.setLayout(FirstChoicesLayout);
        FirstChoicesLayout.setHorizontalGroup(
            FirstChoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FirstChoicesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FirstStronglyDisagree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(44, 44, 44)
                .addComponent(FirstDisagree)
                .addGap(90, 90, 90)
                .addComponent(FirstAgree)
                .addGap(57, 57, 57)
                .addComponent(FirstStronglyAgree))
        );
        FirstChoicesLayout.setVerticalGroup(
            FirstChoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FirstChoicesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FirstChoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstStronglyDisagree)
                    .addComponent(FirstDisagree)
                    .addComponent(FirstAgree)
                    .addComponent(FirstStronglyAgree)))
        );

        FirstQuestion.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        FirstQuestion.setText("1. The grading system was clearly explained to me by my teacher/professor.");

        SecondQuestion.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        SecondQuestion.setText("<html> 2. I received prompt and constructive feedback from my teacher/professor on how I performed in class and how I can further improve my performance in this class. ");

        ThirdQuestion.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        ThirdQuestion.setText(" 3. I was provided with rubrics/scoring guides for evaluating my performance.");

        SecondChoices.setBackground(new java.awt.Color(0, 102, 51));

        SecondStronglyDisagree.setBackground(new java.awt.Color(0, 102, 51));
        SecondStronglyDisagree.setForeground(new java.awt.Color(255, 204, 0));
        SecondStronglyDisagree.setText("Strongly Disagree");
        SecondStronglyDisagree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecondStronglyDisagreeActionPerformed(evt);
            }
        });

        SecondDisagree.setBackground(new java.awt.Color(0, 102, 51));
        SecondDisagree.setForeground(new java.awt.Color(255, 204, 0));
        SecondDisagree.setText("Disagree");
        SecondDisagree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecondDisagreeActionPerformed(evt);
            }
        });

        SecondAgree.setBackground(new java.awt.Color(0, 102, 51));
        SecondAgree.setForeground(new java.awt.Color(255, 204, 0));
        SecondAgree.setText("Agree");
        SecondAgree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecondAgreeActionPerformed(evt);
            }
        });

        SecondStronglyAgree.setBackground(new java.awt.Color(0, 102, 51));
        SecondStronglyAgree.setForeground(new java.awt.Color(255, 204, 0));
        SecondStronglyAgree.setText("Strongly Agree");
        SecondStronglyAgree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecondStronglyAgreeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SecondChoicesLayout = new javax.swing.GroupLayout(SecondChoices);
        SecondChoices.setLayout(SecondChoicesLayout);
        SecondChoicesLayout.setHorizontalGroup(
            SecondChoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SecondChoicesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SecondStronglyDisagree)
                .addGap(44, 44, 44)
                .addComponent(SecondDisagree)
                .addGap(90, 90, 90)
                .addComponent(SecondAgree)
                .addGap(57, 57, 57)
                .addComponent(SecondStronglyAgree))
        );
        SecondChoicesLayout.setVerticalGroup(
            SecondChoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SecondChoicesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SecondChoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SecondStronglyDisagree)
                    .addComponent(SecondDisagree)
                    .addComponent(SecondAgree)
                    .addComponent(SecondStronglyAgree)))
        );

        ThirdChoices.setBackground(new java.awt.Color(0, 102, 51));

        ThirdStronglyDisagree.setBackground(new java.awt.Color(0, 102, 51));
        ThirdStronglyDisagree.setForeground(new java.awt.Color(255, 204, 0));
        ThirdStronglyDisagree.setText("Strongly Disagree");
        ThirdStronglyDisagree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThirdStronglyDisagreeActionPerformed(evt);
            }
        });

        ThirdDisagree.setBackground(new java.awt.Color(0, 102, 51));
        ThirdDisagree.setForeground(new java.awt.Color(255, 204, 0));
        ThirdDisagree.setText("Disagree");
        ThirdDisagree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThirdDisagreeActionPerformed(evt);
            }
        });

        ThirdAgree.setBackground(new java.awt.Color(0, 102, 51));
        ThirdAgree.setForeground(new java.awt.Color(255, 204, 0));
        ThirdAgree.setText("Agree");
        ThirdAgree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThirdAgreeActionPerformed(evt);
            }
        });

        ThirdStronglyAgree.setBackground(new java.awt.Color(0, 102, 51));
        ThirdStronglyAgree.setForeground(new java.awt.Color(255, 204, 0));
        ThirdStronglyAgree.setText("Strongly Agree");
        ThirdStronglyAgree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThirdStronglyAgreeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ThirdChoicesLayout = new javax.swing.GroupLayout(ThirdChoices);
        ThirdChoices.setLayout(ThirdChoicesLayout);
        ThirdChoicesLayout.setHorizontalGroup(
            ThirdChoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThirdChoicesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ThirdStronglyDisagree)
                .addGap(44, 44, 44)
                .addComponent(ThirdDisagree)
                .addGap(90, 90, 90)
                .addComponent(ThirdAgree)
                .addGap(57, 57, 57)
                .addComponent(ThirdStronglyAgree))
        );
        ThirdChoicesLayout.setVerticalGroup(
            ThirdChoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThirdChoicesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ThirdChoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ThirdStronglyDisagree)
                    .addComponent(ThirdDisagree)
                    .addComponent(ThirdAgree)
                    .addComponent(ThirdStronglyAgree)))
        );

        FourthQuestion.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        FourthQuestion.setText("<html>4. My competence was assessed in terms of mastery of content and demonstration of skills.");

        FourthChoices.setBackground(new java.awt.Color(0, 102, 51));

        FourthStronglyDisagree.setBackground(new java.awt.Color(0, 102, 51));
        FourthStronglyDisagree.setForeground(new java.awt.Color(255, 204, 0));
        FourthStronglyDisagree.setText("Strongly Disagree");
        FourthStronglyDisagree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FourthStronglyDisagreeActionPerformed(evt);
            }
        });

        FourthDisagree.setBackground(new java.awt.Color(0, 102, 51));
        FourthDisagree.setForeground(new java.awt.Color(255, 204, 0));
        FourthDisagree.setText("Disagree");
        FourthDisagree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FourthDisagreeActionPerformed(evt);
            }
        });

        FourthAgree.setBackground(new java.awt.Color(0, 102, 51));
        FourthAgree.setForeground(new java.awt.Color(255, 204, 0));
        FourthAgree.setText("Agree");
        FourthAgree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FourthAgreeActionPerformed(evt);
            }
        });

        FourthStronglyAgree.setBackground(new java.awt.Color(0, 102, 51));
        FourthStronglyAgree.setForeground(new java.awt.Color(255, 204, 0));
        FourthStronglyAgree.setText("Strongly Agree");
        FourthStronglyAgree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FourthStronglyAgreeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FourthChoicesLayout = new javax.swing.GroupLayout(FourthChoices);
        FourthChoices.setLayout(FourthChoicesLayout);
        FourthChoicesLayout.setHorizontalGroup(
            FourthChoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FourthChoicesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FourthStronglyDisagree)
                .addGap(44, 44, 44)
                .addComponent(FourthDisagree)
                .addGap(90, 90, 90)
                .addComponent(FourthAgree)
                .addGap(57, 57, 57)
                .addComponent(FourthStronglyAgree))
        );
        FourthChoicesLayout.setVerticalGroup(
            FourthChoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FourthChoicesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FourthChoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FourthStronglyDisagree)
                    .addComponent(FourthDisagree)
                    .addComponent(FourthAgree)
                    .addComponent(FourthStronglyAgree)))
        );

        FifthQuestion.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        FifthQuestion.setText("<html> 5. I was given examinations that match the course objectives, expected learning outcomes, and online class discussions");

        FifthChoices.setBackground(new java.awt.Color(0, 102, 51));

        FifthStronglyDisagree.setBackground(new java.awt.Color(0, 102, 51));
        FifthStronglyDisagree.setForeground(new java.awt.Color(255, 204, 0));
        FifthStronglyDisagree.setText("Strongly Disagree");
        FifthStronglyDisagree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FifthStronglyDisagreeActionPerformed(evt);
            }
        });

        FifthDisagree.setBackground(new java.awt.Color(0, 102, 51));
        FifthDisagree.setForeground(new java.awt.Color(255, 204, 0));
        FifthDisagree.setText("Disagree");
        FifthDisagree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FifthDisagreeActionPerformed(evt);
            }
        });

        FifthAgree.setBackground(new java.awt.Color(0, 102, 51));
        FifthAgree.setForeground(new java.awt.Color(255, 204, 0));
        FifthAgree.setText("Agree");
        FifthAgree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FifthAgreeActionPerformed(evt);
            }
        });

        FifthStronglyAgree.setBackground(new java.awt.Color(0, 102, 51));
        FifthStronglyAgree.setForeground(new java.awt.Color(255, 204, 0));
        FifthStronglyAgree.setText("Strongly Agree");
        FifthStronglyAgree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FifthStronglyAgreeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FifthChoicesLayout = new javax.swing.GroupLayout(FifthChoices);
        FifthChoices.setLayout(FifthChoicesLayout);
        FifthChoicesLayout.setHorizontalGroup(
            FifthChoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FifthChoicesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FifthStronglyDisagree)
                .addGap(44, 44, 44)
                .addComponent(FifthDisagree)
                .addGap(90, 90, 90)
                .addComponent(FifthAgree)
                .addGap(57, 57, 57)
                .addComponent(FifthStronglyAgree))
        );
        FifthChoicesLayout.setVerticalGroup(
            FifthChoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FifthChoicesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FifthChoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FifthStronglyDisagree)
                    .addComponent(FifthDisagree)
                    .addComponent(FifthAgree)
                    .addComponent(FifthStronglyAgree)))
        );

        Next.setBackground(new java.awt.Color(0, 102, 51));
        Next.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Next.setForeground(new java.awt.Color(255, 204, 0));
        Next.setText("Next");
        Next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NextMouseClicked(evt);
            }
        });
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });

        Back.setBackground(new java.awt.Color(0, 102, 51));
        Back.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 204, 0));
        Back.setText("Back");
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout YellowPanelLayout = new javax.swing.GroupLayout(YellowPanel);
        YellowPanel.setLayout(YellowPanelLayout);
        YellowPanelLayout.setHorizontalGroup(
            YellowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(YellowPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(YellowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(YellowPanelLayout.createSequentialGroup()
                        .addGroup(YellowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FourthQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ThirdQuestion)
                            .addComponent(FifthQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FourthChoices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SecondQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FirstQuestion))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(YellowPanelLayout.createSequentialGroup()
                        .addGroup(YellowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SecondChoices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ThirdChoices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FirstChoices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(YellowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(FifthChoices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(YellowPanelLayout.createSequentialGroup()
                                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Next, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(89, 172, Short.MAX_VALUE))))
        );
        YellowPanelLayout.setVerticalGroup(
            YellowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(YellowPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(FirstQuestion)
                .addGap(18, 18, 18)
                .addComponent(FirstChoices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SecondQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SecondChoices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ThirdQuestion)
                .addGap(18, 18, 18)
                .addComponent(ThirdChoices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FourthQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FourthChoices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FifthQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FifthChoices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(YellowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Next, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(YellowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(RedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(YellowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FirstStronglyAgreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstStronglyAgreeActionPerformed
      
           if (FirstStronglyAgree.isSelected())
                 FirstStronglyDisagree.setSelected(false);
                 FirstDisagree.setSelected(false);    
                 FirstAgree.setSelected(false); // TODO add your handling code here:
    }//GEN-LAST:event_FirstStronglyAgreeActionPerformed

    private void FirstAgreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstAgreeActionPerformed
            if (FirstAgree.isSelected())
                 FirstStronglyDisagree.setSelected(false);
                 FirstDisagree.setSelected(false);    
                 FirstStronglyAgree.setSelected(false); 
    }//GEN-LAST:event_FirstAgreeActionPerformed

    private void FirstDisagreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstDisagreeActionPerformed
           if (FirstDisagree.isSelected())
                 FirstStronglyDisagree.setSelected(false);
                 FirstAgree.setSelected(false);    
                 FirstStronglyAgree.setSelected(false); 
    }//GEN-LAST:event_FirstDisagreeActionPerformed

    private void FirstStronglyDisagreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstStronglyDisagreeActionPerformed
          if (FirstStronglyDisagree.isSelected()) 
           FirstDisagree.setSelected(false);
           FirstAgree.setSelected(false);    
           FirstStronglyAgree.setSelected(false); 
    }//GEN-LAST:event_FirstStronglyDisagreeActionPerformed

    private void SecondStronglyDisagreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecondStronglyDisagreeActionPerformed
          if (SecondStronglyDisagree.isSelected()) 
           SecondDisagree.setSelected(false);
           SecondAgree.setSelected(false);    
          SecondStronglyAgree.setSelected(false); 
    }//GEN-LAST:event_SecondStronglyDisagreeActionPerformed

    private void SecondDisagreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecondDisagreeActionPerformed
        if (SecondDisagree.isSelected()) 
           SecondStronglyDisagree.setSelected(false);
           SecondAgree.setSelected(false);    
          SecondStronglyAgree.setSelected(false); 
    }//GEN-LAST:event_SecondDisagreeActionPerformed

    private void SecondAgreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecondAgreeActionPerformed
        if (SecondAgree.isSelected()) 
           SecondDisagree.setSelected(false);
           SecondStronglyDisagree.setSelected(false);    
          SecondStronglyAgree.setSelected(false); 
    }//GEN-LAST:event_SecondAgreeActionPerformed

    private void SecondStronglyAgreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecondStronglyAgreeActionPerformed
       if (SecondStronglyAgree.isSelected()) 
           SecondDisagree.setSelected(false);
           SecondAgree.setSelected(false);    
          SecondStronglyDisagree.setSelected(false);
    }//GEN-LAST:event_SecondStronglyAgreeActionPerformed

    private void ThirdStronglyDisagreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThirdStronglyDisagreeActionPerformed
     if (ThirdStronglyDisagree.isSelected()) 
           ThirdDisagree.setSelected(false);
           ThirdAgree.setSelected(false);    
          ThirdStronglyAgree.setSelected(false); 
    }//GEN-LAST:event_ThirdStronglyDisagreeActionPerformed

    private void ThirdDisagreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThirdDisagreeActionPerformed
   if (ThirdDisagree.isSelected()) 
           ThirdStronglyDisagree.setSelected(false);
           ThirdAgree.setSelected(false);    
          ThirdStronglyAgree.setSelected(false);
    }//GEN-LAST:event_ThirdDisagreeActionPerformed

    private void ThirdAgreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThirdAgreeActionPerformed
       if (ThirdDisagree.isSelected()) 
           ThirdStronglyDisagree.setSelected(false);
           ThirdAgree.setSelected(false);    
          ThirdStronglyAgree.setSelected(false); 
    }//GEN-LAST:event_ThirdAgreeActionPerformed

    private void ThirdStronglyAgreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThirdStronglyAgreeActionPerformed
       if (ThirdStronglyAgree.isSelected()) 
           ThirdDisagree.setSelected(false);
           ThirdAgree.setSelected(false);    
          ThirdStronglyDisagree.setSelected(false); 
    }//GEN-LAST:event_ThirdStronglyAgreeActionPerformed

    private void FourthStronglyDisagreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FourthStronglyDisagreeActionPerformed
      if (FourthStronglyDisagree.isSelected()) 
           FourthDisagree.setSelected(false);
           FourthAgree.setSelected(false);    
          FourthStronglyAgree.setSelected(false); 
    }//GEN-LAST:event_FourthStronglyDisagreeActionPerformed

    private void FourthDisagreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FourthDisagreeActionPerformed
        if (FourthDisagree.isSelected()) 
           FourthStronglyDisagree.setSelected(false);
           FourthAgree.setSelected(false);    
          FourthStronglyAgree.setSelected(false); 
    }//GEN-LAST:event_FourthDisagreeActionPerformed

    private void FourthAgreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FourthAgreeActionPerformed
             if (FourthAgree.isSelected()) 
           FourthDisagree.setSelected(false);
           FourthStronglyDisagree.setSelected(false);    
          FourthStronglyAgree.setSelected(false);
    }//GEN-LAST:event_FourthAgreeActionPerformed

    private void FourthStronglyAgreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FourthStronglyAgreeActionPerformed
     if (FourthStronglyAgree.isSelected()) 
           FourthDisagree.setSelected(false);
           FourthAgree.setSelected(false);    
          FourthStronglyDisagree.setSelected(false); 
    }//GEN-LAST:event_FourthStronglyAgreeActionPerformed

    private void FifthStronglyDisagreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FifthStronglyDisagreeActionPerformed
         if (FifthStronglyDisagree.isSelected()) 
           FifthDisagree.setSelected(false);
          FifthAgree.setSelected(false);    
          FifthStronglyAgree.setSelected(false); 
    }//GEN-LAST:event_FifthStronglyDisagreeActionPerformed

    private void FifthDisagreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FifthDisagreeActionPerformed
          if (FifthDisagree.isSelected()) 
           FifthStronglyDisagree.setSelected(false);
          FifthAgree.setSelected(false);    
          FifthStronglyAgree.setSelected(false); 
    }//GEN-LAST:event_FifthDisagreeActionPerformed

    private void FifthAgreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FifthAgreeActionPerformed
        if (FifthAgree.isSelected()) 
           FifthDisagree.setSelected(false);
          FifthStronglyDisagree.setSelected(false);    
          FifthStronglyAgree.setSelected(false);
    }//GEN-LAST:event_FifthAgreeActionPerformed

    private void FifthStronglyAgreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FifthStronglyAgreeActionPerformed
           if (FifthStronglyAgree.isSelected()) 
           FifthDisagree.setSelected(false);
          FifthAgree.setSelected(false);    
          FifthStronglyDisagree.setSelected(false); 
    }//GEN-LAST:event_FifthStronglyAgreeActionPerformed

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
         MoodleMSTeams MMST = new MoodleMSTeams ();
       MMST.setVisible (true);
       MMST.pack();
       MMST.setLocationRelativeTo(null);
       
       this.dispose ();
    }//GEN-LAST:event_NextActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
       StudentLearningAction2 SLA2 = new StudentLearningAction2 ();
       SLA2.setVisible (true);
       SLA2.pack();
       SLA2.setLocationRelativeTo(null);
       
       this.dispose ();
    }//GEN-LAST:event_BackActionPerformed

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
          
    }//GEN-LAST:event_BackMouseClicked

    private void NextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextMouseClicked
       
    }//GEN-LAST:event_NextMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Assessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Assessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Assessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Assessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Assessment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JRadioButton FifthAgree;
    private javax.swing.JPanel FifthChoices;
    private javax.swing.JRadioButton FifthDisagree;
    private javax.swing.JLabel FifthQuestion;
    private javax.swing.JRadioButton FifthStronglyAgree;
    private javax.swing.JRadioButton FifthStronglyDisagree;
    private javax.swing.JRadioButton FirstAgree;
    private javax.swing.JPanel FirstChoices;
    private javax.swing.JRadioButton FirstDisagree;
    private javax.swing.JLabel FirstQuestion;
    private javax.swing.JRadioButton FirstStronglyAgree;
    private javax.swing.JRadioButton FirstStronglyDisagree;
    private javax.swing.JRadioButton FourthAgree;
    private javax.swing.JPanel FourthChoices;
    private javax.swing.JRadioButton FourthDisagree;
    private javax.swing.JLabel FourthQuestion;
    private javax.swing.JRadioButton FourthStronglyAgree;
    private javax.swing.JRadioButton FourthStronglyDisagree;
    private javax.swing.JButton Next;
    private javax.swing.JPanel RedPanel;
    private javax.swing.JRadioButton SecondAgree;
    private javax.swing.JPanel SecondChoices;
    private javax.swing.JRadioButton SecondDisagree;
    private javax.swing.JLabel SecondQuestion;
    private javax.swing.JRadioButton SecondStronglyAgree;
    private javax.swing.JRadioButton SecondStronglyDisagree;
    private javax.swing.JRadioButton ThirdAgree;
    private javax.swing.JPanel ThirdChoices;
    private javax.swing.JRadioButton ThirdDisagree;
    private javax.swing.JLabel ThirdQuestion;
    private javax.swing.JRadioButton ThirdStronglyAgree;
    private javax.swing.JRadioButton ThirdStronglyDisagree;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel YellowPanel;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
