/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Program;

/**
 *
 * @author francis
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }
   
    
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SidePanel = new javax.swing.JPanel();
        TeacherRatingSystemLabel = new javax.swing.JLabel();
        EvaluateLabelPanel = new javax.swing.JPanel();
        EvaluateLabel = new javax.swing.JLabel();
        AboutLabelPanel = new javax.swing.JPanel();
        AboutLabel = new javax.swing.JLabel();
        SeperatorTRS = new javax.swing.JSeparator();
        CloseLabel = new javax.swing.JLabel();
        LogoutLabel = new javax.swing.JLabel();
        LGreenPanel = new javax.swing.JTabbedPane();
        AboutPanel2 = new javax.swing.JPanel();
        ABOUTaboutPanel2 = new javax.swing.JPanel();
        ABOUTaboutLabel2 = new javax.swing.JLabel();
        AboutText = new javax.swing.JLabel();
        EvaluatePanel = new javax.swing.JPanel();
        SubjectPanel = new javax.swing.JPanel();
        SubjectLabel = new javax.swing.JLabel();
        ITEC50Button = new javax.swing.JButton();
        GNED03Button = new javax.swing.JButton();
        GNED01Button = new javax.swing.JButton();
        GNED06Button = new javax.swing.JButton();
        FITT02Button = new javax.swing.JButton();
        GNED12Button = new javax.swing.JButton();
        NSTP02Button = new javax.swing.JButton();
        DCIT23Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 0));
        setPreferredSize(new java.awt.Dimension(915, 547));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SidePanel.setBackground(new java.awt.Color(0, 102, 51));

        TeacherRatingSystemLabel.setBackground(new java.awt.Color(255, 255, 0));
        TeacherRatingSystemLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        TeacherRatingSystemLabel.setForeground(new java.awt.Color(255, 255, 0));
        TeacherRatingSystemLabel.setText("Teacher Rating System");

        EvaluateLabelPanel.setBackground(new java.awt.Color(153, 255, 153));
        EvaluateLabelPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EvaluateLabelPanelMouseClicked(evt);
            }
        });

        EvaluateLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EvaluateLabel.setForeground(new java.awt.Color(255, 255, 0));
        EvaluateLabel.setText("EVALUATE THE TEACHER");

        javax.swing.GroupLayout EvaluateLabelPanelLayout = new javax.swing.GroupLayout(EvaluateLabelPanel);
        EvaluateLabelPanel.setLayout(EvaluateLabelPanelLayout);
        EvaluateLabelPanelLayout.setHorizontalGroup(
            EvaluateLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EvaluateLabelPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EvaluateLabel)
                .addGap(85, 85, 85))
        );
        EvaluateLabelPanelLayout.setVerticalGroup(
            EvaluateLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EvaluateLabelPanelLayout.createSequentialGroup()
                .addComponent(EvaluateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        AboutLabelPanel.setBackground(new java.awt.Color(153, 255, 153));
        AboutLabelPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutLabelPanelMouseClicked(evt);
            }
        });

        AboutLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AboutLabel.setForeground(new java.awt.Color(255, 255, 0));
        AboutLabel.setText("ABOUT");

        javax.swing.GroupLayout AboutLabelPanelLayout = new javax.swing.GroupLayout(AboutLabelPanel);
        AboutLabelPanel.setLayout(AboutLabelPanelLayout);
        AboutLabelPanelLayout.setHorizontalGroup(
            AboutLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutLabelPanelLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(AboutLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AboutLabelPanelLayout.setVerticalGroup(
            AboutLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutLabelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AboutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CloseLabel.setBackground(new java.awt.Color(255, 255, 0));
        CloseLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CloseLabel.setForeground(new java.awt.Color(255, 255, 0));
        CloseLabel.setText("X");
        CloseLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseLabelMouseClicked(evt);
            }
        });

        LogoutLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        LogoutLabel.setForeground(new java.awt.Color(255, 255, 0));
        LogoutLabel.setText("Logout");
        LogoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SidePanelLayout = new javax.swing.GroupLayout(SidePanel);
        SidePanel.setLayout(SidePanelLayout);
        SidePanelLayout.setHorizontalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AboutLabelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addComponent(EvaluateLabelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addGroup(SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SidePanelLayout.createSequentialGroup()
                        .addGroup(SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SidePanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SeperatorTRS, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TeacherRatingSystemLabel)))
                            .addGroup(SidePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(CloseLabel)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SidePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LogoutLabel)))
                .addContainerGap())
        );
        SidePanelLayout.setVerticalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(CloseLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TeacherRatingSystemLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SeperatorTRS, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(EvaluateLabelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(AboutLabelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(LogoutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        getContentPane().add(SidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 570));

        LGreenPanel.setBackground(new java.awt.Color(255, 204, 0));

        AboutPanel2.setBackground(new java.awt.Color(153, 255, 153));
        AboutPanel2.setPreferredSize(new java.awt.Dimension(669, 525));
        AboutPanel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AboutPanel2KeyPressed(evt);
            }
        });

        ABOUTaboutPanel2.setBackground(new java.awt.Color(0, 102, 51));

        ABOUTaboutLabel2.setBackground(new java.awt.Color(255, 255, 255));
        ABOUTaboutLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        ABOUTaboutLabel2.setForeground(new java.awt.Color(255, 255, 0));
        ABOUTaboutLabel2.setText("ABOUT");

        javax.swing.GroupLayout ABOUTaboutPanel2Layout = new javax.swing.GroupLayout(ABOUTaboutPanel2);
        ABOUTaboutPanel2.setLayout(ABOUTaboutPanel2Layout);
        ABOUTaboutPanel2Layout.setHorizontalGroup(
            ABOUTaboutPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ABOUTaboutPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(ABOUTaboutLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        ABOUTaboutPanel2Layout.setVerticalGroup(
            ABOUTaboutPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ABOUTaboutPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ABOUTaboutLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AboutText.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        AboutText.setText("<html>Teacher Rating System program(TRS Program), <BR>is designed to evaluate our teachers easily.  and it  makes easy to understand for those who lack computer knowledge. <BR>  <BR>TRS program aims to be a more efficient and a capable program to evaluate our teachers. <BR>  <BR> The TRS Program is created by the Group 7 of BSCS 1-C s.y 2021-2022 <BR>  <BR> The group 7 includes:  <BR>   <BR>John Francis Laurio  <BR>Kyle Enrico Ligaje<BR>Eubert Andrei Esguerra <BR>Kurt Villegas  </html>");

        javax.swing.GroupLayout AboutPanel2Layout = new javax.swing.GroupLayout(AboutPanel2);
        AboutPanel2.setLayout(AboutPanel2Layout);
        AboutPanel2Layout.setHorizontalGroup(
            AboutPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(ABOUTaboutPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AboutPanel2Layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addComponent(AboutText, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        AboutPanel2Layout.setVerticalGroup(
            AboutPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ABOUTaboutPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AboutText, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        LGreenPanel.addTab("tab2", AboutPanel2);

        EvaluatePanel.setBackground(new java.awt.Color(153, 255, 153));
        EvaluatePanel.setPreferredSize(new java.awt.Dimension(669, 525));
        EvaluatePanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EvaluatePanelKeyPressed(evt);
            }
        });

        SubjectPanel.setBackground(new java.awt.Color(0, 102, 51));

        SubjectLabel.setBackground(new java.awt.Color(255, 255, 0));
        SubjectLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        SubjectLabel.setForeground(new java.awt.Color(255, 255, 0));
        SubjectLabel.setText("1 - Comsci");

        javax.swing.GroupLayout SubjectPanelLayout = new javax.swing.GroupLayout(SubjectPanel);
        SubjectPanel.setLayout(SubjectPanelLayout);
        SubjectPanelLayout.setHorizontalGroup(
            SubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SubjectPanelLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(SubjectLabel)
                .addGap(50, 50, 50))
        );
        SubjectPanelLayout.setVerticalGroup(
            SubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SubjectLabel)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        ITEC50Button.setText("ITEC 50");
        ITEC50Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ITEC50ButtonActionPerformed(evt);
            }
        });

        GNED03Button.setText("GNED 03");
        GNED03Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GNED03ButtonActionPerformed(evt);
            }
        });

        GNED01Button.setText("GNED 01");
        GNED01Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GNED01ButtonActionPerformed(evt);
            }
        });

        GNED06Button.setText("GNED 06");
        GNED06Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GNED06ButtonActionPerformed(evt);
            }
        });

        FITT02Button.setText("FITT 02");
        FITT02Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FITT02ButtonActionPerformed(evt);
            }
        });

        GNED12Button.setText("GNED 12");
        GNED12Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GNED12ButtonActionPerformed(evt);
            }
        });

        NSTP02Button.setText("NSTP 02");
        NSTP02Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NSTP02ButtonActionPerformed(evt);
            }
        });

        DCIT23Button.setText("DCIT23");
        DCIT23Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DCIT23ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EvaluatePanelLayout = new javax.swing.GroupLayout(EvaluatePanel);
        EvaluatePanel.setLayout(EvaluatePanelLayout);
        EvaluatePanelLayout.setHorizontalGroup(
            EvaluatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EvaluatePanelLayout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(SubjectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EvaluatePanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(EvaluatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ITEC50Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(EvaluatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(GNED06Button, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GNED12Button, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DCIT23Button, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(EvaluatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GNED03Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GNED01Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FITT02Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NSTP02Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88))
        );
        EvaluatePanelLayout.setVerticalGroup(
            EvaluatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EvaluatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SubjectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(EvaluatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GNED03Button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ITEC50Button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EvaluatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GNED01Button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GNED06Button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(EvaluatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FITT02Button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GNED12Button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EvaluatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DCIT23Button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NSTP02Button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(213, Short.MAX_VALUE))
        );

        LGreenPanel.addTab("tab3", EvaluatePanel);

        getContentPane().add(LGreenPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, -33, 660, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EvaluateLabelPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EvaluateLabelPanelMouseClicked
          
        LGreenPanel.setSelectedIndex(1);
    }//GEN-LAST:event_EvaluateLabelPanelMouseClicked

    private void AboutLabelPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutLabelPanelMouseClicked
        
        LGreenPanel.setSelectedIndex(0);
    }//GEN-LAST:event_AboutLabelPanelMouseClicked

    private void CloseLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_CloseLabelMouseClicked

    private void AboutPanel2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AboutPanel2KeyPressed

    }//GEN-LAST:event_AboutPanel2KeyPressed

    private void GNED12ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GNED12ButtonActionPerformed
TeacherQualitiesA TeacherQualitiesA = new TeacherQualitiesA ();
     TeacherQualitiesA.setVisible(true);
     TeacherQualitiesA.setLocationRelativeTo(null);      
    }//GEN-LAST:event_GNED12ButtonActionPerformed

    private void EvaluatePanelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EvaluatePanelKeyPressed

    }//GEN-LAST:event_EvaluatePanelKeyPressed

    private void LogoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutLabelMouseClicked
       Login Login = new Login ();
       Login.setVisible (true);
       Login.pack();
       Login.setLocationRelativeTo(null);
   
       this.dispose();
    }//GEN-LAST:event_LogoutLabelMouseClicked

    private void ITEC50ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ITEC50ButtonActionPerformed
     TeacherQualitiesA TeacherQualitiesA = new TeacherQualitiesA ();
     TeacherQualitiesA.setVisible(true);
     TeacherQualitiesA.setLocationRelativeTo(null);
    }//GEN-LAST:event_ITEC50ButtonActionPerformed

    private void GNED06ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GNED06ButtonActionPerformed
     TeacherQualitiesA TeacherQualitiesA = new TeacherQualitiesA ();
     TeacherQualitiesA.setVisible(true);
     TeacherQualitiesA.setLocationRelativeTo(null);
    }//GEN-LAST:event_GNED06ButtonActionPerformed

    private void DCIT23ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DCIT23ButtonActionPerformed
      TeacherQualitiesA TeacherQualitiesA = new TeacherQualitiesA ();
     TeacherQualitiesA.setVisible(true);
     TeacherQualitiesA.setLocationRelativeTo(null);
    }//GEN-LAST:event_DCIT23ButtonActionPerformed

    private void GNED03ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GNED03ButtonActionPerformed
     TeacherQualitiesA TeacherQualitiesA = new TeacherQualitiesA ();
     TeacherQualitiesA.setVisible(true);
     TeacherQualitiesA.setLocationRelativeTo(null);
    }//GEN-LAST:event_GNED03ButtonActionPerformed

    private void GNED01ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GNED01ButtonActionPerformed
      TeacherQualitiesA TeacherQualitiesA = new TeacherQualitiesA ();
     TeacherQualitiesA.setVisible(true);
     TeacherQualitiesA.setLocationRelativeTo(null);
    }//GEN-LAST:event_GNED01ButtonActionPerformed

    private void FITT02ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FITT02ButtonActionPerformed
       TeacherQualitiesA TeacherQualitiesA = new TeacherQualitiesA ();
     TeacherQualitiesA.setVisible(true);
     TeacherQualitiesA.setLocationRelativeTo(null);
    }//GEN-LAST:event_FITT02ButtonActionPerformed

    private void NSTP02ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NSTP02ButtonActionPerformed
     TeacherQualitiesA TeacherQualitiesA = new TeacherQualitiesA ();
     TeacherQualitiesA.setVisible(true);
     TeacherQualitiesA.setLocationRelativeTo(null);
    }//GEN-LAST:event_NSTP02ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
                
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ABOUTaboutLabel2;
    private javax.swing.JPanel ABOUTaboutPanel2;
    private javax.swing.JLabel AboutLabel;
    private javax.swing.JPanel AboutLabelPanel;
    private javax.swing.JPanel AboutPanel2;
    private javax.swing.JLabel AboutText;
    private javax.swing.JLabel CloseLabel;
    private javax.swing.JButton DCIT23Button;
    private javax.swing.JLabel EvaluateLabel;
    private javax.swing.JPanel EvaluateLabelPanel;
    private javax.swing.JPanel EvaluatePanel;
    private javax.swing.JButton FITT02Button;
    private javax.swing.JButton GNED01Button;
    private javax.swing.JButton GNED03Button;
    private javax.swing.JButton GNED06Button;
    private javax.swing.JButton GNED12Button;
    private javax.swing.JButton ITEC50Button;
    private javax.swing.JTabbedPane LGreenPanel;
    private javax.swing.JLabel LogoutLabel;
    private javax.swing.JButton NSTP02Button;
    private javax.swing.JSeparator SeperatorTRS;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JLabel SubjectLabel;
    private javax.swing.JPanel SubjectPanel;
    private javax.swing.JLabel TeacherRatingSystemLabel;
    // End of variables declaration//GEN-END:variables
}
