/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Program;

import javax.swing.JOptionPane;

/**
 *
 * @author francis
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UpperPanel = new javax.swing.JPanel();
        RegisterLabel = new javax.swing.JLabel();
        CloseLabel = new javax.swing.JLabel();
        MidPanel = new javax.swing.JPanel();
        FirstNameLabel = new javax.swing.JLabel();
        LastNameLabel = new javax.swing.JLabel();
        IDNumberLabel = new javax.swing.JLabel();
        RetypePassLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        FirstNameText = new javax.swing.JTextField();
        LastNameText = new javax.swing.JTextField();
        RegisterButton = new javax.swing.JButton();
        ClickhereLabel = new javax.swing.JLabel();
        GradeLabel = new javax.swing.JLabel();
        GradeText = new javax.swing.JTextField();
        IDNumberText = new javax.swing.JTextField();
        ReTypeText = new javax.swing.JTextField();
        PasswordText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UpperPanel.setBackground(new java.awt.Color(0, 102, 51));

        RegisterLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        RegisterLabel.setForeground(new java.awt.Color(255, 255, 0));
        RegisterLabel.setText("Register");

        CloseLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CloseLabel.setForeground(new java.awt.Color(255, 255, 0));
        CloseLabel.setText("X");
        CloseLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout UpperPanelLayout = new javax.swing.GroupLayout(UpperPanel);
        UpperPanel.setLayout(UpperPanelLayout);
        UpperPanelLayout.setHorizontalGroup(
            UpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RegisterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CloseLabel)
                .addGap(19, 19, 19))
        );
        UpperPanelLayout.setVerticalGroup(
            UpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpperPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(UpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterLabel)
                    .addComponent(CloseLabel))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        MidPanel.setBackground(new java.awt.Color(153, 255, 153));

        FirstNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        FirstNameLabel.setForeground(new java.awt.Color(0, 102, 51));
        FirstNameLabel.setText("First Name :");

        LastNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LastNameLabel.setForeground(new java.awt.Color(0, 102, 51));
        LastNameLabel.setText("Last Name :");

        IDNumberLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        IDNumberLabel.setForeground(new java.awt.Color(0, 102, 51));
        IDNumberLabel.setText("ID Number :");

        RetypePassLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RetypePassLabel.setForeground(new java.awt.Color(0, 102, 51));
        RetypePassLabel.setText("Re-type Password :");

        PasswordLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(0, 102, 51));
        PasswordLabel.setText("Password :");

        FirstNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameTextActionPerformed(evt);
            }
        });
        FirstNameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FirstNameTextKeyPressed(evt);
            }
        });

        LastNameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LastNameTextKeyPressed(evt);
            }
        });

        RegisterButton.setBackground(new java.awt.Color(0, 102, 51));
        RegisterButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RegisterButton.setForeground(new java.awt.Color(255, 255, 0));
        RegisterButton.setText("Register");
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        ClickhereLabel.setForeground(new java.awt.Color(255, 255, 0));
        ClickhereLabel.setText("Click here to Login");
        ClickhereLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClickhereLabelMouseClicked(evt);
            }
        });

        GradeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        GradeLabel.setForeground(new java.awt.Color(0, 102, 51));
        GradeLabel.setText("Grade :");

        IDNumberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDNumberTextActionPerformed(evt);
            }
        });
        IDNumberText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IDNumberTextKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout MidPanelLayout = new javax.swing.GroupLayout(MidPanel);
        MidPanel.setLayout(MidPanelLayout);
        MidPanelLayout.setHorizontalGroup(
            MidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MidPanelLayout.createSequentialGroup()
                .addGroup(MidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MidPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ClickhereLabel)
                        .addGap(166, 166, 166)
                        .addComponent(RegisterButton))
                    .addGroup(MidPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(MidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LastNameLabel)
                            .addComponent(FirstNameLabel)
                            .addComponent(GradeLabel)
                            .addComponent(IDNumberLabel)
                            .addComponent(PasswordLabel)
                            .addComponent(RetypePassLabel))
                        .addGap(18, 18, 18)
                        .addGroup(MidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FirstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GradeText, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReTypeText, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        MidPanelLayout.setVerticalGroup(
            MidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MidPanelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(MidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FirstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(MidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GradeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GradeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(IDNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RetypePassLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ReTypeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(MidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClickhereLabel)
                    .addComponent(RegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UpperPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(MidPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(UpperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(MidPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseLabelMouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_CloseLabelMouseClicked

    private void FirstNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameTextActionPerformed

    }//GEN-LAST:event_FirstNameTextActionPerformed

    private void FirstNameTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FirstNameTextKeyPressed
        char b = evt.getKeyChar();

        if(Character.isLetter(b) || Character.isWhitespace(b) || Character.isISOControl(b)){
            FirstNameText.setEditable(true);
        }else
        {
            FirstNameText.setEditable(false);
        }
    }//GEN-LAST:event_FirstNameTextKeyPressed

    private void LastNameTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LastNameTextKeyPressed
        char b = evt.getKeyChar();

        if(Character.isLetter(b) || Character.isWhitespace(b) || Character.isISOControl(b)){
            LastNameText.setEditable(true);
          
        }else
        {
            LastNameText.setEditable(false);
        }
    }//GEN-LAST:event_LastNameTextKeyPressed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        if (FirstNameText.getText().length() <=0 || LastNameText.getText().length() <=0 || GradeText.getText().length() <=0 || PasswordText.getText().length() <=0 ||  ReTypeText.getText().length() <=0 || IDNumberText.getText().length() <=0)
        {
           JOptionPane.showMessageDialog(null,"Oops! You left a blank");
                    }
        else
        {
        JOptionPane.showMessageDialog(null,"Successfully Registered");
        Login log = new Login ();
        log.setVisible (true);
        log.pack();
        log.setLocationRelativeTo(null);

        this.dispose();
        } 
       
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void ClickhereLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClickhereLabelMouseClicked
        Login log = new Login ();
        log.setVisible (true);
        log.pack();
        log.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_ClickhereLabelMouseClicked

    private void IDNumberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDNumberTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDNumberTextActionPerformed

    private void IDNumberTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDNumberTextKeyPressed
        char a = evt.getKeyChar();
        if (Character.isLetter(a)){
            IDNumberText.setEditable(false);
        } else
        {
            IDNumberText.setEditable(true);
        }
    }//GEN-LAST:event_IDNumberTextKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClickhereLabel;
    private javax.swing.JLabel CloseLabel;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextField FirstNameText;
    private javax.swing.JLabel GradeLabel;
    private javax.swing.JTextField GradeText;
    private javax.swing.JLabel IDNumberLabel;
    private javax.swing.JTextField IDNumberText;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JTextField LastNameText;
    private javax.swing.JPanel MidPanel;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JTextField PasswordText;
    private javax.swing.JTextField ReTypeText;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JLabel RegisterLabel;
    private javax.swing.JLabel RetypePassLabel;
    private javax.swing.JPanel UpperPanel;
    // End of variables declaration//GEN-END:variables
}
